import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms and Conditions — Memorey",
  description:
    "Terms and Conditions governing your access to and use of Memorey.ai.",
};

const sections = [
  {
    heading: "1. Description of Service",
    paragraphs: [
      'Memorey.ai provides a cloud-based knowledge infrastructure tool that allows users to create, store, and organize information into "Nodes," "Vaults," and "Knowledge Graphs" using AI-assisted tools.',
    ],
  },
  {
    heading: "2. Eligibility & Account Registration",
    items: [
      [
        "Accurate Information",
        "You must provide accurate and complete information when creating an account.",
      ],
      [
        "Account Security",
        "You are responsible for maintaining the security of your account credentials.",
      ],
      [
        "Account Responsibility",
        "The Service is provided to you as an individual; you are responsible for all activity occurring under your account.",
      ],
    ],
  },
  {
    heading: "3. Intellectual Property Rights",
    subsections: [
      {
        subheading: "A. Your Content",
        text: 'You retain full ownership of all text, notes, files, and data you upload to Memorey.ai ("User Content"). By using the Service, you grant Memorey.ai a limited, worldwide license to host, transmit, and display your content solely for the purpose of providing the Service to you.',
      },
      {
        subheading: "B. Memorey.ai Property",
        text: 'The Service, including its proprietary "Multi-Vault" architecture, user interface, 3D animations, knowledge graph logic, and the Memorey.ai brand, is the exclusive property of the Service provider. You may not copy, modify, or reverse-engineer any part of the platform\'s infrastructure.',
      },
    ],
  },
  {
    heading: "4. AI Interactions and Accuracy",
    items: [
      [
        "Human-in-the-Loop",
        "Memorey.ai uses AI to suggest the creation of nodes and connections. You acknowledge that you are responsible for reviewing and confirming all nodes and information generated by the AI before they are finalized in your graph.",
      ],
      [
        "No Warranty",
        'Because AI can "hallucinate" or provide inaccurate information, Memorey.ai provides the Service on an "as-is" basis. We do not guarantee the accuracy, completeness, or usefulness of any AI-generated suggestions.',
      ],
    ],
  },
  {
    heading: "5. Subscription, Billing, and Refunds",
    subsections: [
      {
        subheading: "A. Freemium Model",
        text: 'We offer a free tier with limited features and a paid "Pro" tier with expanded capabilities.',
      },
      {
        subheading: "B. Cancellation and Downgrading",
        text: "You may cancel your paid subscription at any time. Upon cancellation, you will retain Pro access until the end of your current billing cycle. After this date, your account will automatically downgrade to the Free Tier. On the Free Tier, you will retain the ability to export your data once, but you will be restricted from creating new Nodes, Vaults, Graphs, or Kanban articles.",
      },
      {
        subheading: "C. No Refunds",
        text: "Payments are non-refundable. If you are charged for a billing cycle, you will have access for the remainder of that period, but no partial refunds will be issued for unused time.",
      },
    ],
  },
  {
    heading: "6. Prohibited Conduct",
    intro: "You agree not to use Memorey.ai to:",
    bullets: [
      "Upload any content that is illegal, infringing, or harmful.",
      "Attempt to disrupt the Service's cloud infrastructure or security measures.",
      "Use the Service to generate automated spam or malicious content.",
    ],
  },
  {
    heading: "7. Limitation of Liability",
    paragraphs: [
      'To the maximum extent permitted by law, Memorey.ai and its developer shall not be liable for any indirect, incidental, or consequential damages resulting from your use of the Service, data loss, or reliance on AI-generated content. Your use of the Service is at your own risk.',
    ],
  },
  {
    heading: "8. Termination",
    paragraphs: [
      "We reserve the right to suspend or terminate your account if you violate these Terms. You may terminate your account at any time by requesting data erasure at hey@memorey.co.",
    ],
  },
  {
    heading: "9. Governing Law",
    paragraphs: [
      "These Terms shall be governed by and construed in accordance with the laws of India, without regard to its conflict of law provisions. Any disputes shall be subject to the exclusive jurisdiction of the courts in Bengaluru, India.",
    ],
  },
  {
    heading: "10. Changes to Terms",
    paragraphs: [
      "We may modify these Terms at any time. We will notify you of significant changes via email or through a notice within the Service. Continued use of the Service after changes constitutes acceptance of the new Terms.",
    ],
  },
] as const;

export default function TermsPage() {
  return (
    <div
      className="min-h-screen"
      style={{ backgroundColor: "var(--bg)", color: "var(--text)" }}
    >
      <header
        className="sticky top-0 z-30 flex items-center justify-between border-b px-6 py-4"
        style={{
          backgroundColor: "var(--bg)",
          borderColor: "var(--border)",
        }}
      >
        <Link
          href="/"
          className="flex items-center gap-2 no-underline"
          style={{ color: "var(--text)" }}
        >
          <div
            className="h-2 w-2 rounded-full"
            style={{ background: "var(--orange)" }}
          />
          <span
            className="text-lg font-bold"
            style={{ fontFamily: "var(--font-syne)" }}
          >
            memorey
          </span>
        </Link>

        <Link
          href="/"
          className="text-xs no-underline transition-opacity hover:opacity-80"
          style={{ color: "var(--muted)" }}
        >
          Back to home
        </Link>
      </header>

      <main className="mx-auto max-w-2xl px-6 py-16 pb-24">
        <p
          className="text-xs font-semibold uppercase tracking-[0.12em]"
          style={{ color: "var(--orange)" }}
        >
          Legal
        </p>

        <h1
          className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl"
          style={{ fontFamily: "var(--font-syne)" }}
        >
          Terms and Conditions
        </h1>

        <p className="mt-4 text-sm" style={{ color: "var(--muted)" }}>
          Effective Date: April 11, 2026 &middot; Last Updated: April 11, 2026
        </p>

        <p
          className="mt-8 leading-relaxed"
          style={{ color: "var(--text2, var(--text))", fontSize: 15 }}
        >
          These Terms and Conditions (&ldquo;Terms&rdquo;) govern your access to
          and use of Memorey.ai (&ldquo;the Service&rdquo;). By creating an
          account or using the Service, you agree to be bound by these Terms.
        </p>

        <div className="mt-12 space-y-12">
          {sections.map((s) => (
            <section key={s.heading}>
              <h2
                className="text-lg font-semibold tracking-tight"
                style={{ fontFamily: "var(--font-syne)" }}
              >
                {s.heading}
              </h2>

              {"intro" in s && s.intro && (
                <p
                  className="mt-3 text-sm leading-relaxed"
                  style={{ color: "var(--text2, var(--text))" }}
                >
                  {s.intro}
                </p>
              )}

              {"items" in s &&
                s.items && (
                  <dl className="mt-4 space-y-4">
                    {(s.items as readonly (readonly [string, string])[]).map(
                      ([term, desc]) => (
                        <div key={term}>
                          <dt
                            className="text-sm font-medium"
                            style={{ color: "var(--text)" }}
                          >
                            {term}
                          </dt>
                          <dd
                            className="mt-1 text-sm leading-relaxed"
                            style={{ color: "var(--text2, var(--text))" }}
                          >
                            {desc}
                          </dd>
                        </div>
                      ),
                    )}
                  </dl>
                )}

              {"subsections" in s &&
                s.subsections && (
                  <div className="mt-4 space-y-5">
                    {(
                      s.subsections as readonly {
                        subheading: string;
                        text: string;
                      }[]
                    ).map((sub) => (
                      <div key={sub.subheading}>
                        <h3
                          className="text-sm font-semibold"
                          style={{ color: "var(--text)" }}
                        >
                          {sub.subheading}
                        </h3>
                        <p
                          className="mt-1 text-sm leading-relaxed"
                          style={{ color: "var(--text2, var(--text))" }}
                        >
                          {sub.text}
                        </p>
                      </div>
                    ))}
                  </div>
                )}

              {"bullets" in s &&
                s.bullets && (
                  <ul
                    className="mt-4 list-disc space-y-1 pl-5 text-sm"
                    style={{ color: "var(--text2, var(--text))" }}
                  >
                    {(s.bullets as readonly string[]).map((b) => (
                      <li key={b}>{b}</li>
                    ))}
                  </ul>
                )}

              {"paragraphs" in s &&
                s.paragraphs &&
                (s.paragraphs as readonly string[]).map((p) => (
                  <p
                    key={p}
                    className="mt-3 text-sm leading-relaxed"
                    style={{ color: "var(--text2, var(--text))" }}
                  >
                    {p}
                  </p>
                ))}
            </section>
          ))}
        </div>

        <section
          className="mt-16 rounded-lg border p-6"
          style={{
            borderColor: "var(--border2)",
            background: "var(--bg2)",
          }}
        >
          <h2
            className="text-lg font-semibold tracking-tight"
            style={{ fontFamily: "var(--font-syne)" }}
          >
            Contact Us
          </h2>
          <p
            className="mt-2 text-sm leading-relaxed"
            style={{ color: "var(--text2, var(--text))" }}
          >
            For any questions regarding these Terms, please contact:
          </p>
          <a
            href="mailto:hey@memorey.co"
            className="mt-3 inline-block text-sm font-medium no-underline transition-opacity hover:opacity-80"
            style={{ color: "var(--orange)" }}
          >
            hey@memorey.co
          </a>
        </section>
      </main>
    </div>
  );
}
