export const VAULTS: Record<
  string,
  { color: string; label: string; desc: string }
> = {
  personal: {
    color: "#FF6600",
    label: "Personal",
    desc: "Who you are & where you've been",
  },
  work: {
    color: "#F5C542",
    label: "Work & Goals",
    desc: "Career, projects & planning",
  },
  health: {
    color: "#FF5B8A",
    label: "Health",
    desc: "Wellbeing, fitness & emotions",
  },
  lifestyle: {
    color: "#4FC1E9",
    label: "Lifestyle",
    desc: "Habits, hobbies & preferences",
  },
  study: {
    color: "#A8E063",
    label: "Study",
    desc: "Knowledge & learning",
  },
  finance: {
    color: "#C792EA",
    label: "Finance",
    desc: "Protected vault",
  },
};

export function mkn(
  id: number,
  x: number,
  y: number,
  r: number,
  vault: string,
  label: string,
  detail: string,
  parent: number | null,
  fresh = false,
  ogImage?: string | null,
) {
  return {
    id,
    x,
    y,
    r,
    vault,
    label,
    detail,
    parent,
    fresh,
    vx: 0,
    vy: 0,
    ogImage: ogImage ?? undefined,
  };
}

/** Demo layout: vault hubs on a wide ring so clusters (nodes + labels) rarely overlap. */
export const SEED_NODES = [
  mkn(
    0,
    0,
    0,
    26,
    "personal",
    "YOU",
    "Your portable memory hub — one graph for every AI you use.",
    null,
  ),
  mkn(1, -240, -70, 16, "personal", "Memories", "Life experiences & events", 0),
  mkn(2, -400, -160, 11, "personal", "Bengaluru", "Home city since 2019", 1),
  mkn(3, -400, 50, 11, "personal", "2019 Trip", "Solo trip to Coorg — life-changing", 1),
  mkn(4, -20, -340, 16, "work", "Work", "Career & planning", 0),
  mkn(5, -200, -460, 11, "work", "Current Project", "Building Memorey — solo dev", 4),
  mkn(6, 120, -400, 11, "work", "Next.js 14", "Primary stack", 4),
  mkn(7, 280, -440, 9, "work", "Supabase", "Database + auth", 6),
  mkn(8, -220, -260, 9, "work", "$3K MRR", "Revenue target Q3 2026", 5),
  mkn(9, 320, -120, 15, "health", "Health", "Wellbeing & fitness", 0),
  mkn(
    10,
    500,
    -240,
    11,
    "health",
    "Vegan",
    "Diet since Jan 2025",
    9,
    true,
    "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=640&q=80",
  ),
  mkn(
    11,
    500,
    40,
    11,
    "health",
    "Running",
    "Marathon training",
    9,
    true,
    "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=640&q=80",
  ),
  mkn(12, 640, -100, 9, "health", "Meditation", "10min daily", 9),
  mkn(13, 320, 200, 14, "lifestyle", "Lifestyle", "Habits & preferences", 0),
  mkn(
    14,
    500,
    320,
    10,
    "lifestyle",
    "Coorg Trips",
    "Visited 3x — hills person",
    13,
    false,
    "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=640&q=80",
  ),
  mkn(15, 150, 320, 10, "lifestyle", "Monsoon", "Favourite season", 13),
  mkn(16, -120, 300, 13, "study", "Study", "Learning & knowledge", 0),
  mkn(17, -300, 440, 9, "study", "DDIA", "Designing Data-Intensive Apps", 16),
  mkn(18, 100, 460, 9, "study", "MCP Protocol", "Model Context Protocol", 16),
  mkn(19, -360, 130, 12, "finance", "Finance", "Protected vault", 0),
  mkn(20, -520, 40, 8, "finance", "Budget", "Protected", 19),
  mkn(21, -500, 240, 8, "finance", "Savings", "Protected", 19),
];

export const SEED_EDGES = SEED_NODES.filter((n) => n.parent !== null).map(
  (n) => ({ a: n.parent as number, b: n.id }),
);

export const MARQUEE_ITEMS = [
  "Identity travels nowhere",
  "Context travels everywhere",
  "You confirm every update",
  "Links deleted after parsing",
  "Works with every AI platform",
  "Export JSON · TOML · Markdown",
  "Zero platform lock-in",
  "One graph. Every AI.",
];

export const PLANS = [
  {
    name: "Free",
    monthlyPrice: 0,
    annualPrice: 0,
    tagline: "Feel what memory-aware AI actually is.",
    cta: "Start free",
    ctaStyle: "ghost" as const,
    featured: false,
    features: [
      "100 memory nodes",
      "3 vaults",
      "5 imports / month",
      "JSON export",
      "Graph view",
    ],
    missing: [] as string[],
    badge: undefined as string | undefined,
  },
  {
    name: "Pro",
    monthlyPrice: 19,
    annualPrice: 15,
    tagline: "For serious AI users who want context everywhere.",
    cta: "Start 14-day trial",
    ctaStyle: "solid" as const,
    featured: true,
    badge: "Best value",
    features: [
      "1,000 memory nodes",
      "All 6 vaults",
      "50 imports / month",
      "JSON · MD · TOML export",
      "Semantic search",
      "Browser extension",
      "MCP server (1 device)",
    ],
    missing: ["API access", "Team graphs"],
  },
  {
    name: "Pro+",
    monthlyPrice: 39,
    annualPrice: 29,
    tagline: "Power users and devs who live inside AI tools.",
    cta: "Get Pro+",
    ctaStyle: "ghost" as const,
    featured: false,
    features: [
      "Unlimited memory nodes",
      "All 6 vaults + custom vaults",
      "Unlimited imports",
      "All export formats",
      "Semantic search",
      "Extension (all browsers)",
      "MCP server (unlimited devices)",
      "REST API access",
      "Node version history",
    ],
    missing: ["Team graphs"],
    badge: undefined,
  },
  {
    name: "Ultra",
    monthlyPrice: 99,
    annualPrice: 79,
    tagline: "Teams & builders who need memory as infrastructure.",
    cta: "Contact us",
    ctaStyle: "ghost" as const,
    featured: false,
    features: [
      "Everything in Pro+",
      "Up to 5 team members",
      "Shared team graph",
      "Vault permissions control",
      "Audit log & history",
      "Priority support (24hr SLA)",
      "Custom onboarding",
      "Early feature access",
    ],
    missing: [] as string[],
    badge: undefined,
  },
];

export type GraphNode = (typeof SEED_NODES)[number];
